
# ignore all warnings from all pods
inhibit_all_warnings!

platform :ios, "7.0"
pod 'Reachability',  '~> 3.0.0'
pod 'AFNetworking', '~> 2.4.1'
pod 'SVProgressHUD', '~> 1.1.3'
pod 'SDWebImage'
pod 'RegexKitLite'
pod 'AFDownloadRequestOperation', '~> 2.0.1'
pod 'Masonry'
pod 'UMengAnalytics-NO-IDFA'
pod 'Qiniu', '~> 7.0'
pod 'MagicalRecord'
pod 'MJRefresh'
pod 'CocoaLumberjack', '~> 2.2.0'